### PR TITLE
bump github.com/lib/pq v1.9.0

### PR DESCRIPTION
**Pull request by thaJeztah**
~this is based on https://github.com/theupdateframework/notary/pull/1445, but~ I'm not too familiar with this dependency, and there's some crypto-changes in here, so I kept it separate 🤗 

full diff: https://github.com/lib/pq/compare/0dad96c0b94f8dee039aa40467f767467392a0af...v1.9.0

### CODE REVIEW

**Comment by thaJeztah** [comment]
ping @justincormack @endophage @cyli ptal

**Comment by thaJeztah** [comment]
making this "WIP", pending https://github.com/theupdateframework/notary/pull/1445

**Comment by thaJeztah** [comment]
rebased, now that https://github.com/theupdateframework/notary/pull/1445 was merged

**Comment by justincormack** [comment]
Hey can you update this to pq 1.2?

**Comment by thaJeztah** [comment]
@justincormack @HuKeping updated to use v1.2.0; ptal

**Comment by HuKeping** [comment]
We don't need `vendor.conf` anymore as per #1539

**Comment by thaJeztah** [comment]
Rebased, and updated to v1.9.0 (latest minor release)

**Comment by thaJeztah** [comment]
hmm.. looks like I need to `go mod tidy`

**Review by HuKeping — APPROVED** [review]
LGTM ! 

Thanks @thaJeztah !

**Pull request merged**
