### PR TITLE
Bump golang.org/x/sys to 314a259e304ff91bd6985da2a7149bbf91237993

### PR DESCRIPTION
**Pull request by thaJeztah**
Commit https://github.com/theupdateframework/notary/commit/8f74d753e3f5226cc60ab9d6cd385da752abc942 (https://github.com/theupdateframework/notary/pull/1234) updated the `golang.org/x/crypto` to master,
however did not update the `golang.org/x/sys` package. 

As a result builds failed in CI:

    # github.com/theupdateframework/notary/vendor/golang.org/x/crypto/ssh/terminal
    vendor/golang.org/x/crypto/ssh/terminal/util_windows.go:42: undefined: windows.ENABLE_ECHO_INPUT
    vendor/golang.org/x/crypto/ssh/terminal/util_windows.go:42: undefined: windows.ENABLE_PROCESSED_INPUT
    vendor/golang.org/x/crypto/ssh/terminal/util_windows.go:42: undefined: windows.ENABLE_LINE_INPUT
    vendor/golang.org/x/crypto/ssh/terminal/util_windows.go:42: undefined: windows.ENABLE_PROCESSED_OUTPUT
    vendor/golang.org/x/crypto/ssh/terminal/util_windows.go:43: undefined: windows.SetConsoleMode
    vendor/golang.org/x/crypto/ssh/terminal/util_windows.go:62: undefined: windows.SetConsoleMode
    vendor/golang.org/x/crypto/ssh/terminal/util_windows.go:67: undefined: windows.ConsoleScreenBufferInfo
    vendor/golang.org/x/crypto/ssh/terminal/util_windows.go:68: undefined: windows.GetConsoleScreenBufferInfo
    vendor/golang.org/x/crypto/ssh/terminal/util_windows.go:91: undefined: windows.ENABLE_ECHO_INPUT
    vendor/golang.org/x/crypto/ssh/terminal/util_windows.go:92: undefined: windows.ENABLE_PROCESSED_INPUT

The `windows.ENABLE_ECHO_INPUT` constant was added in: https://github.com/golang/sys/commit/d6c3f2be455466eedffcfc91793e2c808b7a7410 and was missing

This patch updates the `golang.org/x/sys` package to 314a259e304ff91bd6985da2a7149bbf91237993 (September 26), which is about the same
time as the commit picked for `golang.org/x/crypto`.

Full diff is: https://github.com/golang/sys/compare/739734461d1c916b6c72a63d7efda2b27edb369f...314a259e304ff91bd6985da2a7149bbf91237993

### CODE REVIEW

**Comment by thaJeztah** [comment]
ping @tophj-ibm @endophage @riyazdf PTAL :smile:

**Comment by tophj-ibm** [comment]
Seems good to me.

**Comment by endophage** [comment]
LGTM

**Comment by endophage** [comment]
@riyazdf @ecordell PTAL

**Pull request merged**
