### PR TITLE
Simplify client building and installation instructions.

### PR DESCRIPTION
**Pull request by trishankatdatadog**
Hello there! :)

I'm just simplifying the building and installation instructions to what worked for me.

Let me know what you think!

### CODE REVIEW

**Comment by endophage** [comment]
Jenkins test this please

**Comment by endophage** [comment]
LGTM pending Jenkins (which should bump the codecov too)

**Comment by endophage** [comment]
@trishankatdatadog can you go back and add the signed off by line to the first of the two commits please.

**Comment by trishankatdatadog** [comment]
done :)

**Comment by endophage** [comment]
Jenkins test this please

**Comment by cyli** [comment]
LGTM :)

**Comment by trishankatdatadog** [comment]
Thanks @cyli! Do I need to do anything else here?

**Comment by cyli** [comment]
@trishankatdatadog Nope, this is great, thank you!

**Pull request merged**
