### PR TITLE
Fix gosec linting errors (fix G306 and G307)

### PR DESCRIPTION
**Pull request by thaJeztah**
Carrying the first commit of https://github.com/theupdateframework/notary/pull/1537 (updated the commit message with a description)

### CODE REVIEW

**Comment by thaJeztah** [comment]
@HuKeping @justincormack PTAL

/cc @cquon (hope this is ok with you, as it's not directly related to the change in your PR)

**Comment by justincormack** [comment]
G306 is correct I would say. You should use 0600, although everyone uses 0644 but the default umask converts 0600 to 0644 normally, but you should allow for people with locked down umasks.

**Comment by thaJeztah** [comment]
okay; let me update to use 0600 instead, thx!

**Comment by cquon** [comment]
Awesome thanks @thaJeztah !

**Comment by thaJeztah** [comment]
@justincormack @hukeping updated, PTAL

**Comment by cquon** [comment]
Is this one ready to be merged?

**Comment by HuKeping** [comment]
> Is this one ready to be merged?

@cquon for me, yes.

But I'd like to follow [the merging rule of this project](https://github.com/theupdateframework/notary/blob/master/MAINTAINERS_RULES.md#hard-acceptance-criteria-for-merging-a-pr)

**Pull request merged**
