### PR TITLE
Upgrade docker images to Go 1.13.6

### PR DESCRIPTION
**Pull request by marcofranssen**
Folllowing PR should make the image for the cross.Dockerfile available

Running the ./build-image.sh from that PR should create it locally on your machine for testing purposes.

https://github.com/docker/golang-cross/pull/49

Depending on the other PR we might also take out that change for the cross.Dockerfile so this PR doesn't remain open for ages.

### CODE REVIEW

**Comment by marcofranssen** [comment]
Rebased the branch on top of latest master since merging #1520

**Comment by HuKeping** [comment]
i'm a little worried about the update of golang , it cost quite a lot of time to fix CI when we update it last time.

**Comment by marcofranssen** [comment]
I do think it is worth to invest. Especially for better error handling using errorwrapping and also to have babysteps to be able to upgrade more easily to 1.14 in the near future as there we will benefit from huge performance improvements when it comes to `defer`.

With ther Go 1.13 error wrapping error handling can be simplified and improved.

**Comment by justincormack** [comment]
upgraded to 1.14.1 in #1543

**Pull request closed without merging**
