### PR TITLE
Update Go to 1.9.4

### PR DESCRIPTION
**Pull request by justincormack**
This is a security fix release of Go, see https://go-review.googlesource.com/c/go/+/73392

Some of the fixes may be relevant for Notary.

Signed-off-by: Justin Cormack <justin.cormack@docker.com>

### CODE REVIEW

**Comment by ecordell** [comment]
This LGTM but I'd like to see the tests pass - can someone with circleci permissions rebuild the failing one?

**Comment by endophage** [comment]
Rebuilding CircleCI now. LGTM pending tests.

**Comment by cyli** [comment]
Do we want to merge this or bump up to go 1.9.3?

**Comment by justincormack** [comment]
When i opened this i thought the next release was about to happen so latest
1.8 made sense, but now as 1.10 is almost out so 1.8 will go.out of
support, moving to 1.9 makes sense, will update.

**Comment by justincormack** [comment]
Ok, updated to 1.9.3

**Comment by justincormack** [comment]
Hmm, failing on osx cross build issues that I can't replicate locally...

**Comment by justincormack** [comment]
Of course 1.9.4 is out now, but the Docker images are not yet.

**Comment by cyli** [comment]
Thanks for updating this @justincormack!  Although this is kinda strange - I seem to be getting a bunch of windows related errors when running `make cross` locally:

```
# github.com/theupdateframework/notary/vendor/golang.org/x/crypto/ssh/terminal
vendor/golang.org/x/crypto/ssh/terminal/util_windows.go:42:16: undefined: windows.ENABLE_ECHO_INPUT
vendor/golang.org/x/crypto/ssh/terminal/util_windows.go:42:44: undefined: windows.ENABLE_PROCESSED_INPUT
vendor/golang.org/x/crypto/ssh/terminal/util_windows.go:42:77: undefined: windows.ENABLE_LINE_INPUT
vendor/golang.org/x/crypto/ssh/terminal/util_windows.go:42:105: undefined: windows.ENABLE_PROCESSED_OUTPUT
vendor/golang.org/x/crypto/ssh/terminal/util_windows.go:43:12: undefined: windows.SetConsoleMode
vendor/golang.org/x/crypto/ssh/terminal/util_windows.go:62:9: undefined: windows.SetConsoleMode
vendor/golang.org/x/crypto/ssh/terminal/util_windows.go:67:11: undefined: windows.ConsoleScreenBufferInfo
vendor/golang.org/x/crypto/ssh/terminal/util_windows.go:68:12: undefined: windows.GetConsoleScreenBufferInfo
vendor/golang.org/x/crypto/ssh/terminal/util_windows.go:91:10: undefined: windows.ENABLE_ECHO_INPUT
vendor/golang.org/x/crypto/ssh/terminal/util_windows.go:92:9: undefined: windows.ENABLE_PROCESSED_INPUT
vendor/golang.org/x/crypto/ssh/terminal/util_windows.go:92:9: too many errors
```

I resolved this by re-vendoring a more recent version of `golang.org/x/sys`. 

The errors do seem to be happening in CI too, but it's not failing the build for some reason.

**Comment by justincormack** [comment]
Ok, updated to 1.9.4 and updated the x/sys vendoring, builds fine locally.

**Comment by justincormack** [comment]
Ok, I can see why the test passed, but fixing it shows some other issues...

**Comment by justincormack** [comment]
Ok, fixed the cross build script to error out correctly, and also fixed the pkcs11 issues that showed up from that in addition to the Windows issues by updating that package.

**Comment by endophage** [comment]
@thaJeztah had a PR I've merged to just bump golang.org/x/sys. Can we reset that vendored package against master to remove the conflicts.

**Comment by justincormack** [comment]
Ok removed and rebased.

**Comment by endophage** [comment]
LGTM

**Pull request merged**
