### PR TITLE
Add permission to ConfigureRepo function

### PR DESCRIPTION
**Pull request by molepigeon**
Fixes https://github.com/theupdateframework/notary/issues/1308

Signed-off-by: Michael Hough <michaelh@uk.ibm.com>

### CODE REVIEW

**Comment by molepigeon** [comment]
I think this could use a unit test to prevent a similar regression, but I'm not familiar enough with the existing tests to see something I could modify to test this. Could someone point me in the right direction, and I'll write one 🙂

**Comment by justincormack** [comment]
I think it would be fine to have a test that uses the public docker notary instance (maybe behind a test flag in case people want to disable this) - it seems hard to set up anything more localised.

**Comment by justincormack** [comment]
Aside from test LGTM.

**Comment by endophage** [comment]
Jenkins test this please

**Comment by HuKeping** [comment]
seems rebase needed :-)

**Comment by molepigeon** [comment]
Rebased and added tests.

**Comment by justincormack** [comment]
This needs a rebase. @cyli @molepigeon can we get this merged!

**Comment by molepigeon** [comment]
@justincormack @cyli rebase done. IMO it'd be best to go with fixing the tests in a separate PR, to avoid blocking this any further.

**Pull request merged**
