### PR TITLE
Add Justin Cormack to Maintainers

### PR DESCRIPTION
**Pull request by justincormack**
Thanks for inviting me ;)

TUF work...

Signed-off-by: Justin Cormack <justin.cormack@docker.com>

### CODE REVIEW

**Comment by HuKeping** [comment]
LGTM! 

Welcome on board @justincormack !

**Comment by cyli** [comment]
@endophage @JustinCappos If either if you have time, would you mind adding @justincormack to the notary maintainers team?

**Comment by JustinCappos** [comment]
Okay, done!

**Comment by cyli** [comment]
@justincormack Thanks!

**Comment by endophage** [comment]
@cyli apologies, you asked me to add Justin to the maintainers and it completely slipped my mind by the time I was free.

**Comment by cyli** [comment]
@endophage No worries!  I had totally forgotten that Justin could add maintainers too!  :)

**Comment by thaJeztah** [comment]
:tada:

**Comment by eiais** [comment]
According to the rules to become a notary maintainer, this didn't have the correct number of votes to be merged.

**Comment by cyli** [comment]
We emailed the maintainers on the mailing list and got approval from everyone. According to the process the proposed maintainer shouldn’t open a PR until the existing maintainers appprove.  Possibly we should amend the process do that the order is different, if we wanted to have the approval process be in the form of publi LGTMs.

**Comment by eiais** [comment]
It's already in there that it should be public "Existing maintainers publicly mark their approval on the PR."

**Comment by cyli** [comment]
I had interpreted that as the standard 2 LGTM.

**Comment by endophage** [comment]
Intention was we would have a public 2/3rds on the PR. The goal of the email comms in advance was to ensure there will be the backing when the PR opens.

**Comment by cyli** [comment]
Ah ok, apologies about that.  I’ll both submit a patch to clarify and ask folks to approve the PR, although that would be post merge unfortunately.

**Comment by riyazdf** [comment]
post-facto LGTM

**Pull request merged**
