### PR TITLE
Remove vendor.conf as it is no longer used

### PR DESCRIPTION
**Pull request by thaJeztah**
@cquon @justincormack @HuKeping PTAL

### CODE REVIEW

**Comment by HuKeping** [comment]
```
/go/src/github.com/theupdateframework/notary/cmd/notary/keys.go,525,"Deferring unsafe method ""*os.File"" on type ""Close""",MEDIUM,HIGH,defer from.Close(),CWE-
/go/src/github.com/theupdateframework/notary/cmd/notary/keys.go,554,"Deferring unsafe method ""*os.File"" on type ""Close""",MEDIUM,HIGH,defer f.Close(),CWE-
/go/src/github.com/theupdateframework/notary/cmd/notary/util.go,50,Expect WriteFile permissions to be 0600 or less,MEDIUM,HIGH,"ioutil.WriteFile(t.output, payload, 064
```

Shall we use a defer function to close the os.File? 
```
    from, err := os.Open(file)
    if err != nil {
        return err
    }
    deffer from.Close()              // this seems not a good practice and gosec shouting.
```

wondering but why this PR trigger this warning

**Comment by thaJeztah** [comment]
Oh! It's the same as https://github.com/theupdateframework/notary/pull/1537#issuecomment-597589382. The version of the gosec linter is not pinned, and they recently did a new release.

I wanted to keep this change separate as it seemed more clean, but perhaps I should do a quick carry of that first commit

**Comment by thaJeztah** [comment]
Opened https://github.com/theupdateframework/notary/pull/1540 with a carry. Will rebase this one after that

**Comment by HuKeping** [comment]
Thanks @thaJeztah !

LGTM!

**Pull request merged**
