### PR TITLE
Add some filepaths on Fedora where libykcs11 may be found

### PR DESCRIPTION
**Pull request by trishankatdatadog**
I added some filepaths to the shared `libykcs11` library may be found on Fedora after installing `yubico-piv-tool`.

Signed-off-by: Trishank K Kuppusamy <trishank.kuppusamy@datadoghq.com>

### CODE REVIEW

**Comment by endophage** [comment]
Hey, the linting failed:

```
trustmanager/yubikey/pkcs11_linux.go
Makefile:99: recipe for target 'lint' failed
```

**Comment by trishankatdatadog** [comment]
should be fixed now, i hope

**Comment by endophage** [comment]
Jenkins test this please

**Comment by cyli** [comment]
Ah sorry, the "merge master" button in github breaks the DCO.  :|  Unfortunately you have to rebase.  Not sure if this will help the coverage issues, but fingers crossed!

**Comment by trishankatdatadog** [comment]
No problem, sorry about that, let me get around to this ASAP

**Comment by trishankatdatadog** [comment]
I dropped the merge. Hope this helps. Thanks!

**Pull request merged**
