### PR TITLE
bump go-sql-driver/mysql v1.5.0

### PR DESCRIPTION
**Pull request by thaJeztah**
~this is based on https://github.com/theupdateframework/notary/pull/1445, but~ I'm not too familiar with this dependency, and there's some crypto-changes in here, so I kept it separate 🤗 

full diff: https://github.com/go-sql-driver/mysql/compare/v1.3...v1.5.0

### CODE REVIEW

**Comment by thaJeztah** [comment]
ping @justincormack @endophage @cyli ptal

**Comment by thaJeztah** [comment]
ah, need a new dependency;

```
vendor/github.com/sirupsen/logrus/terminal_windows.go:10:2: cannot find package "github.com/konsorten/go-windows-terminal-sequences" in any of:
	/go/src/github.com/theupdateframework/notary/vendor/github.com/konsorten/go-windows-terminal-sequences (vendor tree)
	/usr/local/go/src/github.com/konsorten/go-windows-terminal-sequences (from $GOROOT)
	/go/src/github.com/konsorten/go-windows-terminal-sequences (from $GOPATH)
```

**Comment by justincormack** [comment]
Can we just make these changes on top after we merge the other rather than having three conflicting PRs?

**Comment by thaJeztah** [comment]
I can make this WIP, and rebase once/if the other one is merged

**Comment by HuKeping** [comment]
Something wrong with the checksum of mysql-1.3.0 ? 
```
$ go mod tidy
verifying github.com/go-sql-driver/mysql@v1.3.0/go.mod: checksum mismatch
	downloaded: h1:w0vKJQ3NCGcTjUuyU/61oovz7odPICajiw/3LVYw1XQ=
	go.sum:     h1:zAC/RDZ24gD3HViQzih4MyKcchzm+sOG5ZlKdlhCg5w=

SECURITY ERROR
This download does NOT match an earlier download recorded in go.sum.
The bits may have been replaced on the origin server, or an attacker may
have intercepted the download attempt.

For more information, see 'go help module-auth'.
```

**Comment by thaJeztah** [comment]
Rebased, and updated to v1.5.0

**Comment by HuKeping** [comment]
Thank you @thaJeztah !  

LGTM!

**Review by HuKeping — APPROVED** [review]

**Comment by HuKeping** [comment]
Need a rebase :)

**Comment by thaJeztah** [comment]
rebased 👍

**Pull request merged**
