### PR TITLE
Regenerate testing certificates

### PR DESCRIPTION
**Pull request by marcofranssen**
The test certificates expired.

This PR refreshed the certificates using the shell script in the fixtures folder.

### CODE REVIEW

**Review by seb-bah — APPROVED** [review]

**Comment by stefan-zh** [comment]
I wonder if it's a good idea to include in this PR a removal of the `-u` on this line [regenerateTestingCerts.sh#L174](https://github.com/theupdateframework/notary/blob/master/fixtures/regenerateTestingCerts.sh#L174) that causes this issue with the transient dependency: https://github.com/theupdateframework/notary/issues/1593#issuecomment-812567781

**Comment by marcofranssen** [comment]
@stefan-zh Not sure what you mean by that as I just pulled the repo, ran the script and got these certificates updated without any issues.

**Comment by stefan-zh** [comment]
> @stefan-zh Not sure what you mean by that as I just pulled the repo, ran the script and got these certificates updated without any issues.

@marcofranssen You have the `cfssljson` binary pre-installed. Try removing it and regenerating certificates from scratch:
```
rm $(which cfssljson)
cd ./fixtures
./regenerateTestingCerts.sh
```

**Comment by ioannisgk** [comment]
> I wonder if it's a good idea to include in this PR a removal of the `-u` on this line [regenerateTestingCerts.sh#L174](https://github.com/theupdateframework/notary/blob/master/fixtures/regenerateTestingCerts.sh#L174) that causes this issue with the transient dependency: [#1593 (comment)](https://github.com/theupdateframework/notary/issues/1593#issuecomment-812567781)

I think you may be mistaken, this PR does not remove the -u option, please check [here](https://github.com/marcofranssen/notary/blob/refresh-testing-certs/fixtures/regenerateTestingCerts.sh#L174) 

I have just used notary with the newly created certificates and I see that everything is working perfectly, I think this PR should be merged to master.

Thank you @marcofranssen

**Comment by stefan-zh** [comment]
@ioannisgk I think you misunderstood my suggestion. I am _suggesting_ that this PR should include a removal of the `-u` option on this line [regenerateTestingCerts.sh#L174](https://github.com/theupdateframework/notary/blob/master/fixtures/regenerateTestingCerts.sh#L174). I am proposing this additional change because certificates _might not_ get regenerated properly in some cases and I think this PR is a proper place to add it.

Are there such cases? Yes, there are - this person ran into this issue https://github.com/theupdateframework/notary/issues/1593#issuecomment-812567781 and I ran into the same issue.

Why do we have this issue when we run the `regenerateTestingCerts.sh` script? Because we don't have the `cfssl` binary on our $GOPATH. Because of that `regenerateTestingCerts.sh` will try to get it and compile it. However, there is a transient issue with a dependency of `cfssl` called `github.com/coreos/bbolt`:

> Not a go expert. I think **it may be affected by github.com/coreos/bbolt now redirects to github.com/etcd-io/bbolt or the github.com/etcd-io/bbolt/**

Is this issue solvable? Yes, it is. Someone else had this issue with the `cfssl` dependency, posted the issue on their GitHub repo https://github.com/cloudflare/cfssl/issues/1183 and then someone provided an answer how to fix it: https://github.com/cloudflare/cfssl/issues/1183#issuecomment-812739180

**Comment by marcofranssen** [comment]
@stefan-zh I have applied your suggestion.

**Review by stefan-zh — APPROVED** [review]
These look good to me

**Comment by marcofranssen** [comment]
@seb-bah are we good to merge? can you handle the merge?

**Review by seb-bah — APPROVED** [review]

**Review by seb-bah — APPROVED** [review]

**Comment by seb-bah** [comment]
> @seb-bah are we good to merge? can you handle the merge?

@marcofranssen I just tested this PR and we're good to go! I don't have write access to be able to merge.

**Comment by marcofranssen** [comment]
FYI @justincormack

**Comment by justincormack** [comment]
Thanks!

**Review by justincormack — APPROVED** [review]

**Pull request merged**
