### PR TITLE
Changelogs for 0.6.0 release

### PR DESCRIPTION
**Pull request by cyli**
We haven't done a release in a while, and there have been a lot of great changes.  I went back over the merged PRs and listed the major changes (as opposed to doc, comment, and test changes).

Does this look reasonable?  @theupdateframework/notary-maintainers

### CODE REVIEW

**Comment by cyli** [comment]
@ecordell Yes I was surprised too!  Would you still be LGTM if, once #1307 is merged, I add it to the change log and rebase this branch?

**Comment by ecordell** [comment]
Yep!

**Comment by HuKeping** [comment]
Haven't been here for quite a long time. I've already done my recruitment work and back to the dev team, recently we are focus on a new micro-kernel but finally I could have some time to check in.

**Comment by cyli** [comment]
@HuKeping Yay!!  Welcome back!

**Pull request merged**
