### PR TITLE
linting: fix "Implicit memory aliasing in RangeStmt"

### PR DESCRIPTION
**Pull request by thaJeztah**
wasn't able to get this linting failiure locally for some reason, but CI was failing on this. This is probably goes `G601: Implicit memory aliasing in RangeStmt`, but the linting output is a bit confusing, so not sure which linter is producing it;

```
/go/src/github.com/theupdateframework/notary/tuf/signed/sign.go,103,Implicit memory aliasing in for loop.,MEDIUM,MEDIUM,&sig,CWE-118
make: *** [Makefile:109: lint] Error 1
```

I _think_ this should fix it 🤞

### CODE REVIEW

**Comment by justincormack** [comment]
Hmm, you just confused the pattern matching algorithm for this, but technically it is correct about the aliasing, although it seems to be safe here, maybe there is a better fix.

**Comment by marcofranssen** [comment]
What is the state on this one? I would like to rebase #1559 so we could also handle that one.

**Comment by justincormack** [comment]
Looking at this again this is a good fix.

**Comment by justincormack** [comment]
@marcofranssen sorry about delay please go ahead and rebase...

**Pull request merged**
